<a href="https://colab.research.google.com/github/jin-raii/weather-web-app/blob/main/weather_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [86]:
import pandas as pd
import matplotlib.pyplot as plt
import json
import csv
from datetime import datetime

In [87]:
# with open('/content/gdrive/MyDrive/kathmandu_weather_data/data_kathmandu_weather.json') as f:
#   data = pd.read_json(f)
# # data = json.load('/content/gdrive/MyDrive/kathmandu_weather_data/data_kathmandu_weather.json')
# data.to_csv('/content/gdrive/MyDrive/kathmandu_weather_data/data_kathmandu.weather.csv', encoding='utf-8', index=False)

In [88]:
# df = pd.read_csv('/content/gdrive/MyDrive/kathmandu_weather_data/data_kathmandu.weather.csv')

In [89]:
# df.head()

In [90]:
# def json_to_csv(json_file, csv_file):
#   try:
#     with open(json_file) as f:
#       data = json.load(f)
#       print(data)
#   except Exception as e:
#     print(f'something went wrong: {e}')

#   try:
#     with open(csv_file, 'w', newline='') as f:
#       write_col = csv.DictWriter(f, fieldnames=data[0].keys())
#       write_col.writeheader()

#       for i in data:
#         write_col.writerow(i)
#     print(f'successfully write csv file to {csv_file}')
#   except Exception as e:
#     print(f'something went wrong {e}')

In [91]:
# json_to_csv('/content/gdrive/MyDrive/kathmandu_weather_data/data_kathmandu_weather.json', '/content/gdrive/MyDrive/kathmandu_weather_data/kathmandu.weather.csv')

In [92]:
# df = pd.read_csv('/content/gdrive/MyDrive/kathmandu_weather_data/kathmandu.weather.csv')
# df.head()

In [93]:
def flatten_weather_data(data_list):
    flattened_data = []
    with open(data_list, 'r') as d:
      data = json.load(d)

    for item in data:
        flat_dict = {
            'timestamp': datetime.fromtimestamp(item['timestamp']).strftime('%Y-%m-%d %H:%M:%S'),
            'longitude': item['data']['coord']['lon'],
            'latitude': item['data']['coord']['lat'],
            'weather_id': item['data']['weather'][0]['id'],
            'weather_main': item['data']['weather'][0]['main'],
            'weather_description': item['data']['weather'][0]['description'],
            'temperature': item['data']['main']['temp'],
            'feels_like': item['data']['main']['feels_like'],
            'temp_min': item['data']['main']['temp_min'],
            'temp_max': item['data']['main']['temp_max'],
            'pressure': item['data']['main']['pressure'],
            'humidity': item['data']['main']['humidity'],
            'sea_level': item['data']['main']['sea_level'],
            'ground_level': item['data']['main']['grnd_level'],
            'visibility': item['data']['visibility'],
            'wind_speed': item['data']['wind']['speed'],
            'wind_degree': item['data']['wind']['deg'],
            'clouds_percentage': item['data']['clouds']['all'],
            'country': item['data']['sys']['country'],
            'sunrise': datetime.fromtimestamp(item['data']['sys']['sunrise']).strftime('%Y-%m-%d %H:%M:%S'),
            'sunset': datetime.fromtimestamp(item['data']['sys']['sunset']).strftime('%Y-%m-%d %H:%M:%S'),
            'timezone': item['data']['timezone'],
            'city_id': item['data']['id'],
            'city_name': item['data']['name']
        }
        flattened_data.append(flat_dict)

    return flattened_data

In [94]:
df_ = pd.DataFrame(flatten_weather_data('/content/gdrive/MyDrive/kathmandu_weather_data/data_kathmandu_weather.json'))
df_.head()

,timestamp,longitude,latitude,weather_id,weather_main,weather_description,temperature,feels_like,temp_min,temp_max,...,visibility,wind_speed,wind_degree,clouds_percentage,country,sunrise,sunset,timezone,city_id,city_name
0,2025-02-12 01:44:14,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
1,2025-02-12 01:44:14,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
2,2025-02-12 01:44:14,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
3,2025-02-12 01:59:58,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
4,2025-02-12 01:59:58,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali

In [95]:
df_.to_csv('/content/gdrive/MyDrive/kathmandu_weather_data/kathmandu.weather.csv', encoding='utf-8', index=False)

In [96]:
data = pd.read_csv('/content/gdrive/MyDrive/kathmandu_weather_data/kathmandu.weather.csv')
data.describe()

,longitude,latitude,weather_id,temperature,feels_like,temp_min,temp_max,pressure,humidity,sea_level,ground_level,visibility,wind_speed,wind_degree,clouds_percentage,timezone,city_id
count,63795.000000,6.379500e+04,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.000000,63795.0,63795.0
mean,85.324000,2.771720e+01,757.104836,286.275594,285.549668,286.275594,286.275594,1013.646587,69.152379,1013.646587,849.942848,5266.357865,2.080942,117.674269,33.370092,20700.0,1282682.0
std,0.000002,1.904980e-11,46.382713,3.723176,3.516453,3.723176,3.723176,2.592418,19.063112,2.592418,1.736514,1552.782738,1.629196,105.049298,20.606924,0.0,0.0
min,85.323900,2.771720e+01,701.000000,280.300000,278.970000,280.300000,280.300000,1007.000000,24.000000,1007.000000,846.000000,1500.000000,0.000000,0.000000,20.000000,20700.0,1282682.0
25%,85.324000,2.771720e+01,701.000000,283.300000,282.490000,283.300000,283.300000,1012.000000,55.000000,1012.000000,849.000000,4500.000000,1.030000,0.000000,20.000000,20700.0,1282682.0
50%,85.324000,2.771720e+01,801.000000,285.300000,284.840000,285.300000,285.300000,1014.000000,72.000000,1014.000000,850.000000,6000.000000,1.540000,120.000000,20.000000,20700.0,1282682.0
75%,85.324000,2.771720e+01,801.000000,289.300000,288.410000,289.300000,289.300000,1015.000000,82.000000,1015.000000,851.000000,6000.000000,3.090000,220.000000,40.000000,20700.0,1282682.0
max,85.324000,2.771720e+01,803.000000,293.300000,292.260000,293.300000,293.300000,1019.000000,100.000000,1019.000000,854.000000,8000.000000,7.200000,350.000000,75.000000,20700.0,1282682.0

In [97]:
data.isnull().sum().sum()

0

In [98]:
data.duplicated().sum()

61901

In [99]:
len(data)

63795

In [100]:
data.head()

,timestamp,longitude,latitude,weather_id,weather_main,weather_description,temperature,feels_like,temp_min,temp_max,...,visibility,wind_speed,wind_degree,clouds_percentage,country,sunrise,sunset,timezone,city_id,city_name
0,2025-02-12 01:44:14,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
1,2025-02-12 01:44:14,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
2,2025-02-12 01:44:14,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
3,2025-02-12 01:59:58,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali
4,2025-02-12 01:59:58,85.324,27.7172,701,Mist,mist,281.3,280.64,281.3,281.3,...,2000,1.54,100,20,NP,2025-02-12 00:58:36,2025-02-12 12:07:28,20700,1282682,Thapathali

In [101]:
data.duplicated(subset=['temperature', 'humidity', 'wind_speed', 'pressure'], keep=False).sum()

63795

In [102]:
### group by minute
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63795 entries, 0 to 63794
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            63795 non-null  object
 1   longitude            63795 non-null  float64
 2   latitude             63795 non-null  float64
 3   weather_id           63795 non-null  int64
 4   weather_main         63795 non-null  object
 5   weather_description  63795 non-null  object
 6   temperature          63795 non-null  float64
 7   feels_like           63795 non-null  float64
 8   temp_min             63795 non-null  float64
 9   temp_max             63795 non-null  float64
 10  pressure             63795 non-null  int64
 11  humidity             63795 non-null  int64
 12  sea_level            63795 non-null  int64
 13  ground_level         63795 non-null  int64
 14  visibility           63795 non-null  int64
 15  wind_speed           63795 non-null  float64
 16  wind_degree          63795 non-null  int64
 17  clouds_percentage    63795 non-null  int64
 18  country              63795 non-null  object
 19  sunrise              63795 non-null  object
 20  sunset               63795 non-null  object
 21  timezone             63795 non-null  int64
 22  city_id              63795 non-null  int64
 23  city_name            63795 non-null  object
dtypes: float64(7), int64(10), object(7)
memory usage: 11.7+ MB